/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarChatIndexRouteImport } from './../routes/_sidebar/chat.index'
import { Route as SidebarChatThreadIdRouteImport } from './../routes/_sidebar/chat.$threadId'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarChatIndexRoute = SidebarChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarChatThreadIdRoute = SidebarChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof SidebarProfileRoute
  '/chat/$threadId': typeof SidebarChatThreadIdRoute
  '/chat/': typeof SidebarChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof SidebarProfileRoute
  '/chat/$threadId': typeof SidebarChatThreadIdRoute
  '/chat': typeof SidebarChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/chat/$threadId': typeof SidebarChatThreadIdRoute
  '/_sidebar/chat/': typeof SidebarChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profile' | '/chat/$threadId' | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile' | '/chat/$threadId' | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/profile'
    | '/_sidebar/chat/$threadId'
    | '/_sidebar/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/chat/': {
      id: '/_sidebar/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof SidebarChatIndexRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/chat/$threadId': {
      id: '/_sidebar/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof SidebarChatThreadIdRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarProfileRoute: typeof SidebarProfileRoute
  SidebarChatThreadIdRoute: typeof SidebarChatThreadIdRoute
  SidebarChatIndexRoute: typeof SidebarChatIndexRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarProfileRoute: SidebarProfileRoute,
  SidebarChatThreadIdRoute: SidebarChatThreadIdRoute,
  SidebarChatIndexRoute: SidebarChatIndexRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
